### PR TITLE
upscaled and changed ui

### PR DESCRIPTION
**Pull request by Sai-Binayak**

### CODE REVIEW

**Comment by Sai-Binayak** [comment]
is there any issues? @PandaAnshuman

**Comment by PandaAnshuman** [comment]
Dear @DAddy-is-CODing2  as we are in the last phase of the event we will not be accepting any ui related PR .
Only new features and major needed updates will be merged

**Comment by Sai-Binayak** [comment]
I just changed the bk color and scaling a bit nothing more

**Comment by PandaAnshuman** [comment]
That's why i will not be accepting

**Comment by Sai-Binayak** [comment]
No problem, I understand. Thank you

**Pull request closed without merging**
